[package]
name = "rachel"
version = "0.1.0"
authors = ["Scott Colby <scott@scolby.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
rayon = "1.5.0"
